reconf_parameter: yarn.timeline-service.ttl-enable
component: hbase:HMaster
v1: false
v2: true
testProject: hbase
unitTest: org.apache.hadoop.hbase.master.assignment.TestCloseRegionWhileRSCrash#testRetryBackoff
reconfPoint: -3
result: -1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is -1
v1v1 or v2v2 test failed !!!
reconf_parameter: yarn.timeline-service.ttl-enable
component: hbase:HMaster
v1: false
v2: true
testProject: hbase
unitTest: org.apache.hadoop.hbase.master.assignment.TestCloseRegionWhileRSCrash#testRetryBackoff
reconfPoint: -3
result: -1
failureMessage: Failed after attempts=16, exceptions:
2020-08-26T04:16:49.186Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:49.302Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to 4da634971e72/172.17.0.7:39442 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:49.518Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to 4da634971e72/172.17.0.7:39442 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:49.838Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to 4da634971e72/172.17.0.7:39442 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:50.355Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to 4da634971e72/172.17.0.7:39442 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:51.396Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:53.442Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:57.484Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:07.591Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:17.625Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:27.677Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:37.741Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:57.973Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:18:18.218Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:18:38.445Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:18:58.620Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442

stackTrace: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=16, exceptions:
2020-08-26T04:16:49.186Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:49.302Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to 4da634971e72/172.17.0.7:39442 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:49.518Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to 4da634971e72/172.17.0.7:39442 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:49.838Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to 4da634971e72/172.17.0.7:39442 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:50.355Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.FailedServerException: Call to 4da634971e72/172.17.0.7:39442 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:51.396Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:53.442Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:16:57.484Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:07.591Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:17.625Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:27.677Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:37.741Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:17:57.973Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:18:18.218Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:18:38.445Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
2020-08-26T04:18:58.620Z, RpcRetryingCaller{globalStartTime=1598415409106, pause=100, maxAttempts=16}, java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HTable.put(HTable.java:540)
	at org.apache.hadoop.hbase.master.assignment.TestCloseRegionWhileRSCrash.testRetryBackoff(TestCloseRegionWhileRSCrash.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Call to 4da634971e72/172.17.0.7:39442 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:177)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)
	at org.apache.hadoop.hbase.ipc.BufferCallBeforeInitHandler.userEventTriggered(BufferCallBeforeInitHandler.java:92)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:326)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:312)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:304)
	at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1426)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:326)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:312)
	at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:924)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection.failInit(NettyRpcConnection.java:179)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection.access$500(NettyRpcConnection.java:71)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:267)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:261)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 4da634971e72/172.17.0.7:39442
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at org.apache.hbase.thirdparty.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	... 7 more
Caused by: java.net.ConnectException: Connection refused
	... 11 more



Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
tr.result is 1

Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1

Test vvMode=v1v2
Warn: conflict exitCode = 1 but tr.result = 1
tr.result is -1
v1v2 test failed !!!
reconf_parameter: yarn.timeline-service.ttl-enable
component: hbase:HMaster
v1: false
v2: true
testProject: hbase
unitTest: org.apache.hadoop.hbase.master.assignment.TestCloseRegionWhileRSCrash#testRetryBackoff
reconfPoint: -3
result: -1
failureMessage: none
stackTrace: none


Test vvMode=v1v1
tr.result is 1

Test vvMode=v2v2
tr.result is 1
v1v2 failed with probability 1 out of 50
v1v1v2v2 failed with probability 1 out of 50
result: false positive !!!
Total execution time in seconds : 13784
